include $(PATH_INFO)/Makefile.user.variable

# Image
TAG := alpine

# Build Args
BUILD_PARAMS := --build-arg DUID="$(DUID)" --build-arg DGID="$(DGID)"

# Filepath
PATH_DOCKER := $(PATH_ROOT)/src/alpine
PATH_DOCKERFILE := $(PATH_ROOT)/src/alpine/Dockerfile.edge