image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u $DOCKER_BUILD_USER -p $DOCKER_BUILD_TOKEN
  - apk --no-cache add make

stages:
  - build
  - test
  - release

variables:
  REGISTRY: registry.gitlab.com
  NAMESPACE: jrbeverly-docker
  PROJECT: docker-baseimage
  GIT_COMMIT: ${CI_COMMIT_SHA}
  PREFIX_TAG: ${CI_COMMIT_SHA}-

build:
  stage: build
  script:
    - make -C build/ alpine
    - make -C build/ VERSION=alpine TAG=alpine push

#test:
#  stage: test
#  script:
#    - make -C build/ VERSION=alpine TAG=alpine pull
#    - make -C build/ VERSION=alpine TAG=alpine test
#  dependencies:
#    - build

#release:
#  stage: release
#  script:
#    - make -C build/ VERSION=alpine TAG=alpine pull
#  dependencies:
#    - test

  