image: docker:latest

services:
  - docker:dind

# ---------------------------------------
# Global
# ---------------------------------------

stages:
  - build
  - test
  - deploy

variables:
  STAGING_REGISTRY: registry.gitlab.com
  STAGING_NAMESPACE: jrbeverly-docker
  STAGING_PROJECT: docker-rsvg

  REGISTRY: docker.io
  NAMESPACE: jrbeverly
  PROJECT: rsvg

  GIT_COMMIT: ${CI_COMMIT_SHA}
  TAG_PREFIX: ${CI_PIPELINE_ID}-

# ----------------------------------------
# Prescript
# ----------------------------------------

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - apk --no-cache add make

# ----------------------------------------
# Build
# ----------------------------------------

build:
  stage: build
  script:
    - sh build/build-all.sh
  only:
    - tags
    - /^versions-.*$/
  except:
    - branches

# ----------------------------------------
# Tests
# ----------------------------------------

test:
  stage: test
  script:
    - sh build/test-all.sh
  dependencies:
    - build
  only:
    - tags
    - /^versions-.*$/
  except:
    - branches

# ----------------------------------------
# Deploy
# ----------------------------------------

deploy:
  stage: deploy
  script:
    - docker login -u $DOCKER_BUILD_USER -p $DOCKER_BUILD_TOKEN
    - sh build/deploy-all.sh
  dependencies:
    - test
  only:
    - tags
    - /^versions-.*$/
  except:
    - branches