# Image
TAG := ubuntu

# Build Args
BUILD_PARAMS := --build-arg DUID="9000" --build-arg DGID="9000"

# Filepath
PATH_DOCKER := $(PATH_ROOT)/src/ubuntu
PATH_DOCKERFILE := $(PATH_ROOT)/src/ubuntu/Dockerfile.edge