include $(PATH_INFO)/Makefile.user.variable

# Image
TAG := ubuntu-16.10

# Build Args
BUILD_PARAMS := --build-arg DUID="$(DUID)" --build-arg DGID="$(DGID)"

# Filepath
PATH_DOCKER := $(PATH_ROOT)/src/ubuntu
PATH_DOCKERFILE := $(PATH_ROOT)/src/ubuntu/Dockerfile.16.10