include $(PATH_INFO)/Makefile.user.variable

# Image
TAG := golang

# Build Args
BUILD_PARAMS := --build-arg DUID="$(DUID)" --build-arg DGID="$(DGID)"

# Filepath
PATH_DOCKER := $(PATH_ROOT)/src/golang
PATH_DOCKERFILE := $(PATH_ROOT)/src/golang/Dockerfile